name: Deploy to Elastic Beanstalk

on:
  push:
    branches:
      - main       # Run workflow when code is pushed to 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest   # Install testing framework

      - name: Run tests
        run: |
          pytest              # Run all tests; fails workflow if any test fails

      - name: Zip application
        run: zip -r deploy.zip . -x "*.git*" "*.venv*" "__pycache__/*"

      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.EB_APP_NAME }}
          environment_name: ${{ secrets.EB_ENV_NAME }}
          region: ${{ secrets.AWS_REGION }}
          version_label: v-${{ github.run_number }}-${{ github.sha }}
          deployment_package: deploy.zip
