name: Build-Test-Deploy

on:
  push:
    branches:
      - main  # Trigger on pushes to main

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      # Step 4: Run tests
      - name: Run tests
        run: |
          pytest --maxfail=1 --disable-warnings -v

      # Step 5: Zip application
      - name: Zip application
        run: zip -r deploy.zip . -x "*.git*" -x "venv/*"

      # Step 6: Deploy to Elastic Beanstalk
      - name: Deploy to Elastic Beanstalk
        uses: einaregilsson/beanstalk-deploy@v21
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: ${{ secrets.EB_APP_NAME }}
          environment_name: ${{ secrets.EB_ENV_NAME }}
          region: ${{ secrets.AWS_REGION }}
          version_label: v-${{ github.run_number }}-${{ github.sha }}
          deployment_package: deploy.zip
          wait_for_deployment: true   # Waits for deployment to complete

      # Optional Step 7: Rollback if deployment fails
      # (Beanstalk-deploy action fails automatically if EB health is Red)
